apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-carrier
  chart:
    git: https://github.com/ayhamkassab/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://130.104.229.14:30000
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer0.supplychain-net:7050
    anchorstx: |-
      CtACChgKFggCGgYIk8q+hAYiCmFsbGNoYW5uZWwSswIKsAIKCmFsbGNoYW5uZWwSYxJhCgtBcHBs
      aWNhdGlvbhJSCAESTgoKY2Fycmllck1TUBJAGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0
      ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSABq8ARK5AQoLQXBwbGljYXRpb24SqQEI
      ARKkAQoKY2Fycmllck1TUBKVAQgBGkkKC0FuY2hvclBlZXJzEjoSMAoWChFwZWVyMC5jYXJyaWVy
      LW5ldBCLNwoWChFwZWVyMS5jYXJyaWVyLW5ldBCLNxoGQWRtaW5zGgcKA01TUBIAIgsKB1JlYWRl
      cnMSACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACoGQWRtaW5z

