apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: buyer-net-ca
  namespace: buyer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: buyer-net-ca
  chart:
    git: https://github.com/roch-ba2/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: buyer-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: buyer-admin
    storage:
      storageclassname: buyersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://172.16.0.6:30000
      authpath: buyer-net-auth
      secretcert: secret/crypto/peerOrganizations/buyer-net/ca?ca.buyer-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/buyer-net/ca?buyer-net-CA.key
      secretadminpass: secret/credentials/buyer-net/ca/buyer?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
