apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaincode-install-buyer-peer0-1
  namespace: buyer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: chaincode-install-buyer-peer0-1
  chart:
    git: https://github.com/roch-ba2/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: buyer-net
      network:
        version: 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.buyer-net:7051
      localmspid: buyerMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://172.17.0.6:30000
      authpath: buyer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/buyer-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/buyer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: secret/credentials/buyer-net/git?git_password
      tls: false
    orderer:
      address: orderer0.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: simpleauction
      version: 1
      lang: golang
      maindirectory: .
      repository:
        hostname: "github.com"
        git_username: "roch-ba2"
        url: github.com/roch-ba2/blockchain-automation-framework.git
        branch: master
        path: examples/supplychain-app/fabric/chaincode_rest_server/chaincode/
      endorsementpolicies:  ''
